### PR TITLE
Updated the Git link in line 29

### PR DESCRIPTION
**Pull request by chouticly**
Git path was pointing to the wrong folder, needed to delete the /ClientSim_UnityProject/ part

### CODE REVIEW

**Comment by momo-the-monster** [comment]
recheck

**Comment by momo-the-monster** [comment]
recheck

**Comment by momo-the-monster** [comment]
@chouticly - thank you very much for this fix! I missed it when migrating the repo to the new format. I didn't have the CLA bot set up yet when you first contributed but it's there now - please check out [its comment](https://github.com/vrchat-community/ClientSim/pull/21#issuecomment-1122034229) and sign the CLA by following the instructions.

**Comment by chouticly** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by momo-the-monster — APPROVED** [review]
Approved, thanks!

**Pull request merged**
