### PR TITLE
Fix broken link in the README.md

### PR DESCRIPTION
**Pull request by CakePost**
The last link in the installation was incorrect. This is the link that worked for me: https://github.com/vrchat-community/ClientSim.git?path=/Packages/com.vrchat.ClientSim#vcc

### CODE REVIEW

**Comment by chouticly** [comment]
duplicate of #21

**Comment by momo-the-monster** [comment]
Thank you for the contribution, @CakePost! I missed that line when migrating the repo to its new format where the root is a Unity Project. However, since [@chouticly submitted the same fix first](https://github.com/vrchat-community/ClientSim/pull/21) I will merge their PR if they sign the CLA, and then I will close this out.

FYI I've got [an open PR with instructions on Contributing to the docs](https://github.com/vrchat-community/ClientSim/pull/24) , You were ahead of the curve here as this is in a 'quiet open beta' until the VCC is released into its own Open Beta.

**Comment by JeffersonCan** [comment]
This install does not work 
Nothing happens when I plug the URLS into Package Manager

**Comment by momo-the-monster** [comment]
Fixed in #22

**Pull request closed without merging**
